.PHONY: help

help:
	$(info Helper for counter demo project)

dev:
	echo "{\"url\": \"$(url)\"}" > ./api/url.json
	npm run dev

build:
	echo "{\"url\": \"$(url)\"}" > ./api/url.json
	npm run build
	npm run generate

test:
	npm run test
