version: "3.8"

services:
  app:
    image: maxxx00m/counter-app:latest
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - application

  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4t5
      MYSQL_DATABASE: test_site
      MYSQL_USER: test_site
      MYSQL_PASSWORD: password
    networks:
      - application

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - application

networks:
  application:

volumes:
  mysqldata: