version: "3.8"

services:
  app:
    image: maxxx00m/counter-app:latest
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4t5
      MYSQL_DATABASE: test_site
      MYSQL_USER: test_site
      MYSQL_PASSWORD: password

volumes:
  mysqldata: